services:
  - type: web
    name: propaganda-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python PropagandaBotSeP.py
    envVars:
      - key: GOOGLE_CREDENTIALS_FILE
        value: credentials.json
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.11"
    healthCheckPath: /
    plan: free

