services:
  - type: web
    name: propaganda-bot
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python PropagandaBotSeP.py
    envVars:
      - key: GOOGLE_CREDENTIALS_FILE
        value: credentials.json
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /
    plan: free
